//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Hackathon.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class nal
    {
        [Key]
        public int nalId { get; set; }
        public string strap { get; set; }
        public string folio { get; set; }
        public string dor_cd { get; set; }
        public string val_method { get; set; }
        public string mill_cd { get; set; }
        public string nh_cd { get; set; }
        public string vac_impr_flg { get; set; }
        public string yr_impr { get; set; }
        public string yr_annexed { get; set; }
        public string splt_dt { get; set; }
        public string dsc_cd { get; set; }
        public string base_yr { get; set; }
        public string mkt_ar1 { get; set; }
        public string mkt_ar2 { get; set; }
        public string pr_strap { get; set; }
        public string prob_deed { get; set; }
        public string tenancy { get; set; }
        public string hx_val { get; set; }
        public string wid_val { get; set; }
        public string wdr_val { get; set; }
        public string dis_val { get; set; }
        public string wx_val { get; set; }
        public string jst_val { get; set; }
        public string cls_val { get; set; }
        public string asd_val { get; set; }
        public string soh_val { get; set; }
        public string tax_val { get; set; }
        public string cur_base { get; set; }
        public string pct_soh { get; set; }
        public string mkt_soh { get; set; }
        public string mkt_mkt { get; set; }
        public string ag_x_val { get; set; }
        public string tot_bld_val { get; set; }
        public string cost_bld_val { get; set; }
        public string tot_xf_val { get; set; }
        public string tot_lnd_val { get; set; }
        public string cls_lnd_val { get; set; }
        public string ag_lnd_val { get; set; }
        public string asd_lnd_val { get; set; }
        public string ncon_val { get; set; }
        public string demo_val { get; set; }
        public string comb_val { get; set; }
        public string split_val { get; set; }
        public string px_val { get; set; }
        public string pr_val { get; set; }
        public string ag_x_flg { get; set; }
        public string yr_created { get; set; }
        public string pr_dor_cd { get; set; }
        public string map_id { get; set; }
        public string own_dt { get; set; }
        public string life_est { get; set; }
        public string jt_flg { get; set; }
        public string inc_flg { get; set; }
        public string mh_flg { get; set; }
        public string lnd_sale_flg { get; set; }
        public string conf_flg { get; set; }
        public string mortage_cd { get; set; }
        public string owner1 { get; set; }
        public string owner2 { get; set; }
        public string m_state { get; set; }
        public string m_addr_1 { get; set; }
        public string m_addr_2 { get; set; }
        public string m_city { get; set; }
        public string m_zip { get; set; }
        public string m_country { get; set; }
        public string carr_rt { get; set; }
        public string mailto { get; set; }
        public string str { get; set; }
        public string str_pfx { get; set; }
        public string str_num { get; set; }
        public string str_sfx { get; set; }
        public string str_unit { get; set; }
        public string s_zip { get; set; }
        public string s_city { get; set; }
        public string plat_bk { get; set; }
        public string plat_pg { get; set; }
    }
}
