USE [master]
GO

/****** Object:  Database [HackathonTampa]    Script Date: 04/14/2013 15:59:56 ******/
CREATE DATABASE [HackathonTampa] ON  PRIMARY 
( NAME = N'HackathonTampa_data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\HackathonTampa_data.mdf' , SIZE = 80896KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HackathonTampa_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\HackathonTampa_log.ldf' , SIZE = 52416KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HackathonTampa] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HackathonTampa].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HackathonTampa] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HackathonTampa] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HackathonTampa] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HackathonTampa] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HackathonTampa] SET ARITHABORT OFF 
GO

ALTER DATABASE [HackathonTampa] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HackathonTampa] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [HackathonTampa] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HackathonTampa] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HackathonTampa] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HackathonTampa] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HackathonTampa] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HackathonTampa] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HackathonTampa] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HackathonTampa] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HackathonTampa] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HackathonTampa] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HackathonTampa] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HackathonTampa] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HackathonTampa] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HackathonTampa] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HackathonTampa] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HackathonTampa] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HackathonTampa] SET  READ_WRITE 
GO

ALTER DATABASE [HackathonTampa] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HackathonTampa] SET  MULTI_USER 
GO

ALTER DATABASE [HackathonTampa] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HackathonTampa] SET DB_CHAINING OFF 
GO


